model:
  hidden_channels: 256
  batch_size: 32
  edge_attrs: false

trainer:
  epochs: 8
  device: cuda
  compile: true  # Whether to use torch.compile
  num_workers: 12

optimizer:
  type: Adam
  lr: 0.001

scheduler:
  type: StepLR
  step_size: 1
  gamma: 0.5

data:
  dataset: 'D1'
  subontology: ['MFO']  # One or more from ['CCO', 'MFO', 'BPO']
  train_on_swissprot: False  # Whether to train on SwissProt or original train dataset
  exp_only: true  # If training on SwissProt, whether to use only experimental annotations
  alignment_path: ./data/swissprot/2024_01/diamond_swissprot_2024_01_alignment.tsv  # Alignment TSV
  protein_graphs: ./data/swissprot/2024_01/protein_graphs

run:
  qualifier: 2layerGNN  # Additional string to append to run_id for uniqueness
  save_predictions:
    val: true
    test: true
  test_only: false  # Whether to run evaluation only on the test set (no validation)
  save_model: true
  project_path: "/lustre/fsn1/projects/rech/dqy/uki62ne/tempdata/PFP_layer"

checkpoint:
  dir: ./checkpoints
  load: false
  load_path: ./checkpoints/best_model.pth
