model:
  hidden_channels: 256
  batch_size: 32
  edge_attrs: false 
  edge_types:
    #- ["aa", "close_to", "aa"]
    - ["aa", "belongs_to", "protein"]
    - ["protein", "aligned_with", "protein"]
    #- ["protein", "stringdb", "protein"]

  # How many edges to sample to build mini-batch subgraphs. Follows PyG nomenclature
  sampled_edges:
    protein__aligned_with__protein: -1
    # protein__stringdb__protein: 30

trainer:
  epochs: 1
  device: cuda
  compile: false  # Whether to use torch.compile
  num_workers: 4

optimizer:
  type: Adam
  lr: 0.001

scheduler:
  type: StepLR
  step_size: 1
  gamma: 0.5

data:
  dataset: 'swissprot'
  subontology: 'MFO'
  train_on_swissprot: true  # Override original train dataset to train on SwissProt instead. Ignored if dataset is already SwissProt.
  swissprot_release: '2017_01'  # SwissProt release used.
  exp_only: false  # If training on SwissProt, whether to use only experimental annotations
  alignment_path: ./data/swissprot/2024_01/diamond_swissprot_2024_01_alignment.tsv
  protein_graphs: ./data/swissprot/2024_01/protein_graphs
  stringdb_path: ./data/swissprot/2024_01/swissprot_stringdb.tsv

run:
  qualifier: LONG  # Additional string to append to run_id for uniqueness
  save_predictions:
    val: false
    test: false
  test_only: true  # Whether to run evaluation only on the test set (no validation)
  save_epoch_checkpoints: true  # Whether to save checkpoint for each epoch (in addition to latest)
  run_beprof_eval: false
  run_cafa_eval: false
  project_path: "/lustre/fsn1/projects/rech/dqy/uki62ne/tempdata/PFP_layer"
  #project_path: "/home/atoffano/PFP_layer"
