model:
  hidden_channels: 256
  batch_size: 8
  edge_attrs: true
  edge_types:
    - ["aa", "close_to", "aa"]
    - ["aa", "belongs_to", "protein"]
    - ["protein", "aligned_with", "protein"]
    - ["protein", "stringdb", "protein"]
  interpro: true # Intepro domain annotations as additional input features
  go_neighbors: true # Whether to include direct GO term negihbors as additional input features

  # How many edges to sample to build mini-batch subgraphs. Follows PyG nomenclature
  sampled_edges:
    protein__aligned_with__protein: -1
    protein__stringdb__protein: 30

trainer:
  epochs: 6
  device: cuda
  compile: false  # Whether to use torch.compile
  num_workers: 4

optimizer:
  type: Adam
  lr: 0.001

scheduler:
  type: StepLR
  step_size: 1
  gamma: 0.5

data:
  subontology: 'CCO'
  dataset: 'ATGO' # Dataset to use, which determines test set proteins and default train proteins/annotations.
  train_proteins: 'ATGO'  # Override 'dataset' train proteins with the specified dataset's proteins.
  swissprot_release: '2024_01'  # SwissProt release annotations used when training on SwissProt proteins (train_proteins: swissprot)
  exp_only: true  # Whether to use experimental or curated annotations when training on SwissProt proteins
  external_annotations_path: ./data/swissprot/2024_01/swissprot_2024_01_CCO_exp_annotations.tsv # Override train annotations with a specific annotation file. Also overrides 'exp_only' flag.
  
  alignment_path: ./data/swissprot/2024_01/diamond_swissprot_2024_01_alignment.tsv
  protein_graphs: ./data/swissprot/2024_01/protein_graphs
  stringdb_path: ./data/swissprot/2024_01/swissprot_stringdb.tsv

run:
  qualifier: GNN_CONTACT_ATTR_STRINGDB  # Additional string to append to run_id for uniqueness
  save_predictions:
    val: true
    test: true
  test_only: true  # Whether to run evaluation only on the test set (no validation)
  save_epoch_checkpoints: true  # Whether to save checkpoint for each epoch (in addition to latest)
  run_beprof_eval: true
  run_cafa_eval: true
  project_path: "/lustre/fsn1/projects/rech/dqy/uki62ne/tempdata/PFP_layer"