model:
  hidden_channels: 128
  batch_size: 32

trainer:
  epochs: 1
  device: cuda
  compile: false  # Whether to use torch.compile

optimizer:
  type: Adam
  lr: 0.01

scheduler:
  type: StepLR
  step_size: 5
  gamma: 0.5

data:
  dataset: 'toy'
  subontology: ['BPO']  # One or more from ['CCO', 'MFO', 'BPO']
  train_on_swissprot: False  # Whether to train on SwissProt or original train dataset
  exp_only: True  # If training on SwissProt, whether to use only experimental annotations
  alignment_path: ./data/toy/toy_swissprot_2024_01_alignment.tsv  # Alignment TSV
  protein_graphs: ./data/toy/protein_graphs
  uses_entryid: true

run:
  qualifier: default  # Additional string to append to run_id for uniqueness
  save_predictions:
    val: true
    test: true
  test_only: true  # Whether to run evaluation only on the test set (no validation)
  save_model: false
  #project_path: "/home/atoffano/PFP_layer"  # From constants.py
  project_path: "/lustre/fsn1/projects/rech/dqy/uki62ne/tempdata/PFP_layer"

checkpoint:
  dir: ./checkpoints
  load: false
  load_path: ./checkpoints/best_model.pth
