model:
  hidden_channels: 128
  batch_size: 32
  edge_attrs: false
  edge_types:
    - ["aa", "close_to", "aa"]
    - ["aa", "belongs_to", "protein"]
    - ["protein", "aligned_with", "protein"]
    - ["protein", "stringdb", "protein"]

trainer:
  epochs: 2
  device: cuda
  compile: false  # Whether to use torch.compile
  num_workers: 0

optimizer:
  type: Adam
  lr: 0.001

scheduler:
  type: StepLR
  step_size: 1
  gamma: 0.5

data:
  dataset: 'toy'
  subontology: ['BPO']  # One or more from ['CCO', 'MFO', 'BPO']
  train_on_swissprot: false  # Whether to train on SwissProt or original train dataset
  exp_only: true  # If training on SwissProt, whether to use only experimental annotations
  alignment_path: ./data/toy/toy_swissprot_2024_01_alignment.tsv  # Alignment TSV
  protein_graphs: ./data/toy/protein_graphs
  stringdb_path: ./data/toy/toy_swissprot_stringdb.tsv

run:
  qualifier: default  # Additional string to append to run_id for uniqueness
  save_predictions:
    val: true
    test: true
  test_only: false  # Whether to run evaluation only on the test set (no validation)
  save_model: true
  save_epoch_checkpoints: true  # Whether to save checkpoint for each epoch (in addition to latest)
  #project_path: "/home/atoffano/PFP_layer"  # From constants.py
  project_path: "/lustre/fsn1/projects/rech/dqy/uki62ne/tempdata/PFP_layer"